server:
  port: ${PORT:8865}
message: Configuración de local en el servidor levantado!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudcloud
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8860
